---
# Prometheus configuration file
global:
  scrape_interval: 1m
  scrape_timeout: 30s

rule_files:
  - "/etc/prometheus/rules/*.yml"
  - "/etc/prometheus/conf/rules/*.yml"
  - "/etc/prometheus/config/rules/*.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:9093"

scrape_configs:
  - job_name: devnet_nxos_nodes
    params:
      module:
        - cisco_nxos
      x_token:
        - anonymous
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - devnet-sw01
      labels:
        region: us
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      # the exporter's hostname:port
      replacement: 127.0.0.1:9533
